# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "musicbrainz_ruby"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack"]
  s.date = "2012-07-01"
  s.description = "Musicbrainz.org API Ruby Implementation"
  s.email = ["jack@caged-media.com"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitignore",
    ".idea/.name",
    ".idea/.rakeTasks",
    ".idea/codeStyleSettings.xml",
    ".idea/dictionaries/j4k4x.xml",
    ".idea/encodings.xml",
    ".idea/inspectionProfiles/Project_Default.xml",
    ".idea/inspectionProfiles/profiles_settings.xml",
    ".idea/misc.xml",
    ".idea/modules.xml",
    ".idea/musicbrainz_ruby.iml",
    ".idea/scopes/scope_settings.xml",
    ".idea/vcs.xml",
    ".idea/workspace.xml",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "database.yml",
    "features/musicbrainz_ruby.feature",
    "features/releases/release_query.feature",
    "features/step_definitions/MB/rails_steps.rb",
    "features/step_definitions/MB/release_steps.rb/release_steps.rb",
    "features/support/cukigem.rb",
    "features/support/env.rb",
    "lib/generators/music_brainz/install/initializer_generator.rb",
    "lib/generators/music_brainz/install/install_generator.rb",
    "lib/generators/music_brainz/install/templates/config/initializers/musicbrainz.rb.erb",
    "lib/musicbrainz/artist.rb",
    "lib/musicbrainz/base.rb",
    "lib/musicbrainz/label.rb",
    "lib/musicbrainz/query.rb",
    "lib/musicbrainz/recording.rb",
    "lib/musicbrainz/release.rb",
    "lib/musicbrainz/release_group.rb",
    "lib/musicbrainz/string.rb",
    "lib/musicbrainz/work.rb",
    "lib/musicbrainz_ruby.rb",
    "log/test.log",
    "musicbrainz_ruby.gemspec",
    "report.html",
    "spec/factories.rb",
    "spec/musicbrainz_ruby_spec.rb",
    "spec/spec_helper.rb",
    "tmp/rails_app/.gitignore",
    "tmp/rails_app/Gemfile",
    "tmp/rails_app/Gemfile.lock",
    "tmp/rails_app/README.rdoc",
    "tmp/rails_app/Rakefile",
    "tmp/rails_app/app/assets/images/rails.png",
    "tmp/rails_app/app/assets/javascripts/application.js",
    "tmp/rails_app/app/assets/javascripts/mmbrains.js.coffee",
    "tmp/rails_app/app/assets/stylesheets/application.css",
    "tmp/rails_app/app/assets/stylesheets/mmbrains.css.scss",
    "tmp/rails_app/app/assets/stylesheets/scaffolds.css.scss",
    "tmp/rails_app/app/controllers/application_controller.rb",
    "tmp/rails_app/app/controllers/mmbrains_controller.rb",
    "tmp/rails_app/app/controllers/models_controller.rb",
    "tmp/rails_app/app/helpers/application_helper.rb",
    "tmp/rails_app/app/helpers/mmbrains_helper.rb",
    "tmp/rails_app/app/mailers/.gitkeep",
    "tmp/rails_app/app/models/.gitkeep",
    "tmp/rails_app/app/models/mmbrain.rb",
    "tmp/rails_app/app/views/layouts/application.html.erb",
    "tmp/rails_app/app/views/mmbrains/_form.html.erb",
    "tmp/rails_app/app/views/mmbrains/edit.html.erb",
    "tmp/rails_app/app/views/mmbrains/index.html.erb",
    "tmp/rails_app/app/views/mmbrains/new.html.erb",
    "tmp/rails_app/app/views/mmbrains/show.html.erb",
    "tmp/rails_app/app/views/models/show.html.erb",
    "tmp/rails_app/config.ru",
    "tmp/rails_app/config/application.rb",
    "tmp/rails_app/config/boot.rb",
    "tmp/rails_app/config/database.yml",
    "tmp/rails_app/config/environment.rb",
    "tmp/rails_app/config/environments/development.rb",
    "tmp/rails_app/config/environments/production.rb",
    "tmp/rails_app/config/environments/test.rb",
    "tmp/rails_app/config/initializers/backtrace_silencers.rb",
    "tmp/rails_app/config/initializers/inflections.rb",
    "tmp/rails_app/config/initializers/mime_types.rb",
    "tmp/rails_app/config/initializers/secret_token.rb",
    "tmp/rails_app/config/initializers/session_store.rb",
    "tmp/rails_app/config/initializers/wrap_parameters.rb",
    "tmp/rails_app/config/locales/en.yml",
    "tmp/rails_app/config/routes.rb",
    "tmp/rails_app/db/migrate/20120630070553_create_mmbrains.rb",
    "tmp/rails_app/db/seeds.rb",
    "tmp/rails_app/lib/assets/.gitkeep",
    "tmp/rails_app/lib/tasks/.gitkeep",
    "tmp/rails_app/log/.gitkeep",
    "tmp/rails_app/public/404.html",
    "tmp/rails_app/public/422.html",
    "tmp/rails_app/public/500.html",
    "tmp/rails_app/public/favicon.ico",
    "tmp/rails_app/public/index.html",
    "tmp/rails_app/public/robots.txt",
    "tmp/rails_app/script/rails",
    "tmp/rails_app/test/fixtures/.gitkeep",
    "tmp/rails_app/test/fixtures/mmbrains.yml",
    "tmp/rails_app/test/functional/.gitkeep",
    "tmp/rails_app/test/functional/mmbrains_controller_test.rb",
    "tmp/rails_app/test/integration/.gitkeep",
    "tmp/rails_app/test/performance/browsing_test.rb",
    "tmp/rails_app/test/test_helper.rb",
    "tmp/rails_app/test/unit/.gitkeep",
    "tmp/rails_app/test/unit/helpers/mmbrains_helper_test.rb",
    "tmp/rails_app/test/unit/mmbrain_test.rb",
    "tmp/rails_app/vendor/assets/javascripts/.gitkeep",
    "tmp/rails_app/vendor/assets/stylesheets/.gitkeep",
    "tmp/rails_app/vendor/plugins/.gitkeep"
  ]
  s.homepage = "http://ror.caged-media.com"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Make Musicbrainz API calls within RoR"
  s.test_files = ["features/musicbrainz_ruby.feature", "features/releases/release_query.feature", "features/step_definitions/MB/rails_steps.rb", "features/step_definitions/MB/release_steps.rb/release_steps.rb", "features/support/cukigem.rb", "features/support/env.rb", "spec/factories.rb", "spec/musicbrainz_ruby_spec.rb", "spec/spec_helper.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.2.6"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<sprockets>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<factory_girl>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.5.0"])
      s.add_development_dependency(%q<webrat>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<pickle>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<spork-rails>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.2.6"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<sprockets>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 1.5.0"])
      s.add_dependency(%q<webrat>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<pickle>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<spork-rails>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.2.6"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<sprockets>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 1.5.0"])
    s.add_dependency(%q<webrat>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<pickle>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<spork-rails>, [">= 0"])
  end
end

