# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "musicbrainz_ruby"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack"]
  s.date = "2012-07-02"
  s.description = "Musicbrainz.org API Ruby Implementation"
  s.email = ["jack@caged-media.com"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitignore",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/musicbrainz_ruby.feature",
    "features/releases/release_query.feature",
    "features/step_definitions/MB/rails_steps.rb",
    "features/step_definitions/MB/release_steps.rb/release_steps.rb",
    "features/step_definitions/web_steps.rb",
    "features/support/cukigem.rb",
    "features/support/env.rb",
    "features/support/paths.rb",
    "lib/generators/music_brainz/install/initializer_generator.rb",
    "lib/generators/music_brainz/install/install_generator.rb",
    "lib/generators/music_brainz/install/templates/config/initializers/musicbrainz.rb.erb",
    "lib/musicbrainz/artist.rb",
    "lib/musicbrainz/base.rb",
    "lib/musicbrainz/label.rb",
    "lib/musicbrainz/query.rb",
    "lib/musicbrainz/recording.rb",
    "lib/musicbrainz/release.rb",
    "lib/musicbrainz/release_group.rb",
    "lib/musicbrainz/string.rb",
    "lib/musicbrainz/work.rb",
    "lib/musicbrainz_ruby.rb",
    "log/test.log",
    "musicbrainz_ruby.gemspec",
    "report.html",
    "spec/factories.rb",
    "spec/musicbrainz_ruby_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://ror.caged-media.com"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Make Musicbrainz API calls within RoR"
  s.test_files = ["features/musicbrainz_ruby.feature", "features/releases/release_query.feature", "features/step_definitions/MB/rails_steps.rb", "features/step_definitions/MB/release_steps.rb/release_steps.rb", "features/step_definitions/web_steps.rb", "features/support/cukigem.rb", "features/support/env.rb", "features/support/paths.rb", "spec/factories.rb", "spec/musicbrainz_ruby_spec.rb", "spec/spec_helper.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.2.6"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<sprockets>, [">= 0"])
      s.add_development_dependency(%q<pickle>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<factory_girl>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.5.0"])
      s.add_development_dependency(%q<webrat>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<pickle>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<spork-rails>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.2.6"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<sprockets>, [">= 0"])
      s.add_dependency(%q<pickle>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 1.5.0"])
      s.add_dependency(%q<webrat>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<pickle>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<spork-rails>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.2.6"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<sprockets>, [">= 0"])
    s.add_dependency(%q<pickle>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 1.5.0"])
    s.add_dependency(%q<webrat>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<pickle>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<spork-rails>, [">= 0"])
  end
end

