
    source 'https://rubygems.org'
			gem 'rails', '3.2.6'
			gem 'sqlite3'
			group :assets do
			  gem 'sass-rails',   '~> 3.2.3'
			  gem 'coffee-rails', '~> 3.2.1'
			  gem 'therubyracer', :platforms => :ruby
			  gem 'uglifier', '>= 1.0.3'
			end
			gem 'jquery-rails'
  
    group :test do
			gem "guard-rspec"
		  gem "factory_girl_rails", ">= 1.6.0"
		  gem "cucumber-rails", ">= 1.2.1"
		  gem "capybara", ">= 1.1.2"
		  gem "database_cleaner"
		  gem "launchy"
		end
  gem "musicbrainz_ruby","0.1.0",:path=>'/home/j4k4x/musicbrainz_ruby/pkg/'